# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9894b2c8badff35d71529263db41fc5e"
name = "visual-search-dev-partners-old"
handle = "visual-search-dev-partners-old"
application_url = "https://astronomy-bryant-parents-count.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_products"

[auth]
redirect_urls = ["https://astronomy-bryant-parents-count.trycloudflare.com/auth/callback", "https://astronomy-bryant-parents-count.trycloudflare.com/auth/shopify/callback", "https://astronomy-bryant-parents-count.trycloudflare.com/api/auth/callback"]

[app_proxy]
url = "https://astronomy-bryant-parents-count.trycloudflare.com/api"
subpath = "api"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
