# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ca33b33ed019e099b184e93807bb1159"
name = "visual-search-deploy"
handle = "visual-search-deploy"
application_url = "https://slides-mailed-ripe-dozens.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_products"

[auth]
redirect_urls = ["https://slides-mailed-ripe-dozens.trycloudflare.com/auth/callback", "https://slides-mailed-ripe-dozens.trycloudflare.com/auth/shopify/callback", "https://slides-mailed-ripe-dozens.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
