# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ca33b33ed019e099b184e93807bb1159"
name = "Visual Search (Deployed)"
handle = "visual-search-deploy"
application_url = "https://cooking-peninsula-val-finnish.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_products"

[auth]
redirect_urls = ["https://cooking-peninsula-val-finnish.trycloudflare.com/auth/callback", "https://cooking-peninsula-val-finnish.trycloudflare.com/auth/shopify/callback", "https://cooking-peninsula-val-finnish.trycloudflare.com/api/auth/callback"]

[app_proxy]
url = "https://cooking-peninsula-val-finnish.trycloudflare.com/api"
subpath = "api"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
